{{-- contains main background and elements of home page --}}
{{-- use in Home/index --}}
<div id="rev_slider_24_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-source="gallery" style="margin:0px auto;background:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
    <div id="rev_slider_24_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.4.8.1">
        <ul>
            {{-- main background --}}
            <li data-index="rs-54" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="1000" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                <img src="{{ asset('storage/images/background/bg.jpg') }}" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>


                {{-- shadow layer on background image --}}
                <div class="tp-caption tp-shape tp-shapewrapper" id="slide-54-layer-27" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['0','0','0','0']" data-width="full" data-height="full" data-whitespace="nowrap" data-type="shape" data-basealign="slide" data-responsive_offset="off" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]"
                    style="z-index: 5;background:linear-gradient(50deg, rgba(15,90,224,0.7) 00%, rgba(116,0,186,0.7) 100%);"></div>

                {{-- logo in the middle of slider section --}}
                <div class="tp-caption tp-shape tp-shapewrapper" id="slide-54-layer-9" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['193','141','141','141']" data-width="['480','340','340','340']" data-height="['639','486','486','486']" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1500,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]"
                    style="z-index: 6;border-color:rgba(255,255,255,0.1);border-style:solid;border-width:5px 5px 5px 5px;">
                    <div style="position: absolute;" class="rs-looped rs-pulse" data-easing="Quad.easeInOut" data-speed="1.1" data-zoomstart=".95" data-zoomend="1.02">
                        <img style=" opacity: 0.45; position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);" src="{{ asset('storage/images/logo/etminanlogo.png') }}" alt="">
                    </div>
                </div>
                <div class="tp-caption tp-shape tp-shapewrapper" id="slide-54-layer-10" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['163','110','110','110']" data-width="['540','400','400','400']" data-height="['700','550','550','550']" data-whitespace="nowrap" data-type="shape" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1500,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]"
                    style="z-index: 7;border-color:rgba(255,255,255,0.1);border-style:solid;border-width:5px 5px 5px 5px;">
                    <div class="rs-looped rs-pulse" data-easing="Power0.easeInOut" data-speed="1" data-zoomstart="1" data-zoomend="1.05"></div>
                </div>


                {{-- elements of home page --}}
                <div class="tp-caption rs-parallaxlevel-2" id="slide-54-layer-11" data-x="['left','left','left','left']" data-hoffset="['138','90','90','90']" data-y="['top','top','top','top']" data-voffset="['180','100','100','100']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1000,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 8;"><img
                        style="width: 10px; height: 30px;" src="{{ asset('storage/images/background/lt.png') }}" alt="" data-ww="" data-hh="" data-no-retina></div>
                <div class="tp-caption rs-parallaxlevel-1" id="slide-54-layer-12" data-x="['left','left','left','left']" data-hoffset="['138','54','54','54']" data-y="['top','top','top','top']" data-voffset="['595','394','394','394']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1000,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 9;"><img
                        src="{{ asset('storage/images/background/lm.png') }}" alt="" data-ww="" data-hh="" data-no-retina></div>
                <div class="tp-caption rs-parallaxlevel-3" id="slide-54-layer-13" data-x="['left','left','left','left']" data-hoffset="['400','144','144','144']" data-y="['top','top','top','top']" data-voffset="['693','526','526','526']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1000,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 10;"><img
                        src="{{ asset('storage/images/background/lb.png') }}" alt="" data-ww="" data-hh="" data-no-retina></div>
                <div class="tp-caption rs-parallaxlevel-4" id="slide-54-layer-14" data-x="['right','right','right','right']" data-hoffset="['138','90','90','90']" data-y="['top','top','top','top']" data-voffset="['180','100','100','100']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1000,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 11;"><img
                        src="{{ asset('storage/images/background/rt.png') }}" alt="" data-ww="['179px','179px','179px','179px']" data-hh="['162px','162px','162px','162px']" data-no-retina></div>
                <div class="tp-caption rs-parallaxlevel-1" id="slide-54-layer-15" data-x="['right','right','right','right']" data-hoffset="['138','48','48','48']" data-y="['top','top','top','top']" data-voffset="['546','398','398','398']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1000,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 12;"><img
                        src="{{ asset('storage/images/background/rm.png') }}" alt="" data-ww="['145px','145px','145px','145px']" data-hh="['92px','92px','92px','92px']" data-no-retina></div>
                <div class="tp-caption rs-parallaxlevel-2" id="slide-54-layer-17" data-x="['right','right','right','right']" data-hoffset="['360','52','52','52']" data-y="['top','top','top','top']" data-voffset="['659','550','550','550']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1000,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13;"><img
                        src="{{ asset('storage/images/background/rb.png') }}" alt="" data-ww="['142auto','142auto','142auto','142auto']" data-hh="['112px','112px','112px','112px']" data-no-retina></div>


                {{-- <div class="tp-caption rs-parallaxlevel-2" id="slide-54-layer-18" data-x="['right','right','right','right']" data-hoffset="['60','152','152','152']" data-y="['top','top','top','top']" data-voffset="['659','550','550','550']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":1000,"frame":"0","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"frame":"999","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 13;"> data-ww="['142auto','142auto','142auto','142auto']" data-hh="['112px','112px','112px','112px']" data-no-retina> </div> --}}





                {{-- <div class="tp-caption" id="slide-54-layer-18" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['334','253','225','225']" data-fontsize="['72','54','40','40']" data-lineheight="['78','58','42','42']" data-width="['980','750','576','576']" data-height="['157','none','85','85']" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames='[{"delay":10,"split":"chars","splitdelay":0.05,"speed":1000,"split_direction":"forward","frame":"0","from":"y:[100%];z:0;rZ:-35deg;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power4.easeInOut"},{"delay":"wait","speed":800,"frame":"999","to":"y:[100%];","mask":"x:inherit;y:inherit;s:inherit;e:inherit;","ease":"nothing"}]' data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 14; min-width: 980px; max-width: 980px; max-width: 157px; max-width: 157px; white-space: normal; font-size: 72px; line-height: 78px; font-weight: 700; color: #ffffff; letter-spacing: 0px;font-family:Montserrat;text-transform:uppercase;"> --}}
                {{-- بستنی اطمینان </div> --}}


                <div class="tp-caption" id="slide-54-layer-19" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['top','top','top','top']" data-voffset="['784','576','576','576']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','on','off']" data-type="image" data-actions='[{"event":"click","action":"scrollbelow","offset":"-230px","delay":"","speed":"500","ease":"Linear.easeNone"}]' data-responsive_offset="on" data-responsive="off" data-frames='[{"delay":10,"speed":800,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":800,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']"
                    data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 15;cursor:pointer;">
                    <div class="rs-looped rs-slideloop" data-easing="Linear.easeNone" data-speed="1" data-xs="0" data-xe="0" data-ys="-8" data-ye="8"><img src="{{ asset('storage/images/background/touch.png') }}" alt="" data-ww="" data-hh="" data-no-retina></div>
                </div>
                <div class="tp-caption" id="slide-54-layer-23" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['-1','-1','-1','-1']" data-width="full" data-height="none" data-whitespace="nowrap" data-visibility="['on','on','off','off']" data-type="image" data-basealign="slide" data-responsive_offset="on" data-frames='[{"delay":10,"speed":300,"frame":"0","from":"opacity:0;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":300,"frame":"999","to":"opacity:0;","ease":"Power3.easeInOut"}]' data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 16;">
                    <img src="{{ asset('storage/images/background/ImgBottomborder.png') }}" alt="" data-ww="['full','full','full','full']" data-hh="" data-no-retina></div>

            </li>
        </ul>
        {{-- <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div> --}}
    </div>
</div>
